//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.15 at 09:15:47 PM CEST 
//


package org.musicxml.v31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * The stick type represents pictograms where the material of the stick, mallet, or beater is included.The parentheses and dashed-circle attributes indicate the presence of these marks around the round beater part of a pictogram. Values for these attributes are "no" if not present.
 * 
 * <p>Java class for stick complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="stick">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stick-type" type="{}stick-type"/>
 *         &lt;element name="stick-material" type="{}stick-material"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tip" type="{}tip-direction" />
 *       &lt;attribute name="parentheses" type="{}yes-no" />
 *       &lt;attribute name="dashed-circle" type="{}yes-no" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "stick", propOrder = {
    "stickType",
    "stickMaterial"
})
public class Stick {

    @XmlElement(name = "stick-type", required = true)
    @XmlSchemaType(name = "string")
    protected StickType stickType;
    @XmlElement(name = "stick-material", required = true)
    @XmlSchemaType(name = "string")
    protected StickMaterial stickMaterial;
    @XmlAttribute(name = "tip")
    protected TipDirection tip;
    @XmlAttribute(name = "parentheses")
    protected YesNo parentheses;
    @XmlAttribute(name = "dashed-circle")
    protected YesNo dashedCircle;

    /**
     * Gets the value of the stickType property.
     * 
     * @return
     *     possible object is
     *     {@link StickType }
     *     
     */
    public StickType getStickType() {
        return stickType;
    }

    /**
     * Sets the value of the stickType property.
     * 
     * @param value
     *     allowed object is
     *     {@link StickType }
     *     
     */
    public void setStickType(StickType value) {
        this.stickType = value;
    }

    /**
     * Gets the value of the stickMaterial property.
     * 
     * @return
     *     possible object is
     *     {@link StickMaterial }
     *     
     */
    public StickMaterial getStickMaterial() {
        return stickMaterial;
    }

    /**
     * Sets the value of the stickMaterial property.
     * 
     * @param value
     *     allowed object is
     *     {@link StickMaterial }
     *     
     */
    public void setStickMaterial(StickMaterial value) {
        this.stickMaterial = value;
    }

    /**
     * Gets the value of the tip property.
     * 
     * @return
     *     possible object is
     *     {@link TipDirection }
     *     
     */
    public TipDirection getTip() {
        return tip;
    }

    /**
     * Sets the value of the tip property.
     * 
     * @param value
     *     allowed object is
     *     {@link TipDirection }
     *     
     */
    public void setTip(TipDirection value) {
        this.tip = value;
    }

    /**
     * Gets the value of the parentheses property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getParentheses() {
        return parentheses;
    }

    /**
     * Sets the value of the parentheses property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setParentheses(YesNo value) {
        this.parentheses = value;
    }

    /**
     * Gets the value of the dashedCircle property.
     * 
     * @return
     *     possible object is
     *     {@link YesNo }
     *     
     */
    public YesNo getDashedCircle() {
        return dashedCircle;
    }

    /**
     * Sets the value of the dashedCircle property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNo }
     *     
     */
    public void setDashedCircle(YesNo value) {
        this.dashedCircle = value;
    }

}
