//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.15 at 09:15:47 PM CEST 
//


package org.musicxml.v31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for enclosure-shape.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="enclosure-shape">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="rectangle"/>
 *     &lt;enumeration value="square"/>
 *     &lt;enumeration value="oval"/>
 *     &lt;enumeration value="circle"/>
 *     &lt;enumeration value="bracket"/>
 *     &lt;enumeration value="triangle"/>
 *     &lt;enumeration value="diamond"/>
 *     &lt;enumeration value="pentagon"/>
 *     &lt;enumeration value="hexagon"/>
 *     &lt;enumeration value="heptagon"/>
 *     &lt;enumeration value="octagon"/>
 *     &lt;enumeration value="nonagon"/>
 *     &lt;enumeration value="decagon"/>
 *     &lt;enumeration value="none"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "enclosure-shape")
@XmlEnum
public enum EnclosureShape {

    @XmlEnumValue("rectangle")
    RECTANGLE("rectangle"),
    @XmlEnumValue("square")
    SQUARE("square"),
    @XmlEnumValue("oval")
    OVAL("oval"),
    @XmlEnumValue("circle")
    CIRCLE("circle"),
    @XmlEnumValue("bracket")
    BRACKET("bracket"),
    @XmlEnumValue("triangle")
    TRIANGLE("triangle"),
    @XmlEnumValue("diamond")
    DIAMOND("diamond"),
    @XmlEnumValue("pentagon")
    PENTAGON("pentagon"),
    @XmlEnumValue("hexagon")
    HEXAGON("hexagon"),
    @XmlEnumValue("heptagon")
    HEPTAGON("heptagon"),
    @XmlEnumValue("octagon")
    OCTAGON("octagon"),
    @XmlEnumValue("nonagon")
    NONAGON("nonagon"),
    @XmlEnumValue("decagon")
    DECAGON("decagon"),
    @XmlEnumValue("none")
    NONE("none");
    private final java.lang.String value;

    EnclosureShape(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static EnclosureShape fromValue(java.lang.String v) {
        for (EnclosureShape c: EnclosureShape.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
