//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.15 at 09:15:47 PM CEST 
//


package org.musicxml.v31;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * The harmon-closed type represents whether the harmon mute is closed, open, or half-open. The optional location attribute indicates which portion of the symbol is filled in when the element value is half.
 * 
 * <p>Java class for harmon-closed complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="harmon-closed">
 *   &lt;simpleContent>
 *     &lt;extension base="&lt;>harmon-closed-value">
 *       &lt;attribute name="location" type="{}harmon-closed-location" />
 *     &lt;/extension>
 *   &lt;/simpleContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "harmon-closed", propOrder = {
    "value"
})
public class HarmonClosed {

    @XmlValue
    protected HarmonClosedValue value;
    @XmlAttribute(name = "location")
    protected HarmonClosedLocation location;

    /**
     * The harmon-closed-value type represents whether the harmon mute is closed, open, or half-open.
     * 
     * @return
     *     possible object is
     *     {@link HarmonClosedValue }
     *     
     */
    public HarmonClosedValue getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link HarmonClosedValue }
     *     
     */
    public void setValue(HarmonClosedValue value) {
        this.value = value;
    }

    /**
     * Gets the value of the location property.
     * 
     * @return
     *     possible object is
     *     {@link HarmonClosedLocation }
     *     
     */
    public HarmonClosedLocation getLocation() {
        return location;
    }

    /**
     * Sets the value of the location property.
     * 
     * @param value
     *     allowed object is
     *     {@link HarmonClosedLocation }
     *     
     */
    public void setLocation(HarmonClosedLocation value) {
        this.location = value;
    }

}
