//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.06.15 at 09:15:47 PM CEST 
//


package org.musicxml.v31;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for wood.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="wood">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="bamboo scraper"/>
 *     &lt;enumeration value="board clapper"/>
 *     &lt;enumeration value="cabasa"/>
 *     &lt;enumeration value="castanets"/>
 *     &lt;enumeration value="castanets with handle"/>
 *     &lt;enumeration value="claves"/>
 *     &lt;enumeration value="football rattle"/>
 *     &lt;enumeration value="guiro"/>
 *     &lt;enumeration value="log drum"/>
 *     &lt;enumeration value="maraca"/>
 *     &lt;enumeration value="maracas"/>
 *     &lt;enumeration value="quijada"/>
 *     &lt;enumeration value="rainstick"/>
 *     &lt;enumeration value="ratchet"/>
 *     &lt;enumeration value="reco-reco"/>
 *     &lt;enumeration value="sandpaper blocks"/>
 *     &lt;enumeration value="slit drum"/>
 *     &lt;enumeration value="temple block"/>
 *     &lt;enumeration value="vibraslap"/>
 *     &lt;enumeration value="whip"/>
 *     &lt;enumeration value="wood block"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "wood")
@XmlEnum
public enum Wood {

    @XmlEnumValue("bamboo scraper")
    BAMBOO_SCRAPER("bamboo scraper"),
    @XmlEnumValue("board clapper")
    BOARD_CLAPPER("board clapper"),
    @XmlEnumValue("cabasa")
    CABASA("cabasa"),
    @XmlEnumValue("castanets")
    CASTANETS("castanets"),
    @XmlEnumValue("castanets with handle")
    CASTANETS_WITH_HANDLE("castanets with handle"),
    @XmlEnumValue("claves")
    CLAVES("claves"),
    @XmlEnumValue("football rattle")
    FOOTBALL_RATTLE("football rattle"),
    @XmlEnumValue("guiro")
    GUIRO("guiro"),
    @XmlEnumValue("log drum")
    LOG_DRUM("log drum"),
    @XmlEnumValue("maraca")
    MARACA("maraca"),
    @XmlEnumValue("maracas")
    MARACAS("maracas"),
    @XmlEnumValue("quijada")
    QUIJADA("quijada"),
    @XmlEnumValue("rainstick")
    RAINSTICK("rainstick"),
    @XmlEnumValue("ratchet")
    RATCHET("ratchet"),
    @XmlEnumValue("reco-reco")
    RECO_RECO("reco-reco"),
    @XmlEnumValue("sandpaper blocks")
    SANDPAPER_BLOCKS("sandpaper blocks"),
    @XmlEnumValue("slit drum")
    SLIT_DRUM("slit drum"),
    @XmlEnumValue("temple block")
    TEMPLE_BLOCK("temple block"),
    @XmlEnumValue("vibraslap")
    VIBRASLAP("vibraslap"),
    @XmlEnumValue("whip")
    WHIP("whip"),
    @XmlEnumValue("wood block")
    WOOD_BLOCK("wood block");
    private final java.lang.String value;

    Wood(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static Wood fromValue(java.lang.String v) {
        for (Wood c: Wood.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
