version: '3'
name: playin
services:
  solr:
    image: playin_solr:@solr.version@
    build:
      dockerfile: playin_solr.Dockerfile
    ports:
      - "8983:8983"
      - "8000:8000"
    volumes:
      - solr_home:/var/solr
    environment:
      # For debugging on port 8000
      SOLR_OPTS: -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
      # For verbose output of solr scripts
      # VERBOSE: yes
  solr_cors:
    image: playin_solr_cors:@solr.version@
    build:
      dockerfile: playin_solr_cors.Dockerfile
    ports:
      - "8983:8983"
      - "8000:8000"
    volumes:
      - solr_home:/var/solr
    environment:
      # For debugging on port 8000
      SOLR_OPTS: -agentlib:jdwp=transport=dt_socket,address=*:8000,server=y,suspend=n
      # For verbose output of solr scripts
      # VERBOSE: yes
  apache:
    image: httpd:2.4
    ports:
      - '8080:80'
    volumes:
      - ./website:/usr/local/apache2/htdocs
volumes:
  solr_home:
